name: Build

on:
  release:
    types: [published]
  push:
    branches:
    - master
  
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    
    - name: Perm
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app.apk
        path: ./app/build/outputs/apk/debug/app-debug.apk
